cryostatio/cryostat

.github/workflows/ci.yaml
=> ci(jdk): use JDK 21 rather than 20

.github/dependabot.yml
=> build(dependabot): add dependabot config

src/main/docker/Dockerfile.jvm, src/main/docker/Dockerfile.legacy-jar, src/main/resources/application-test.properties
=> fix(itest): correct JAVA_OPTS for JAVA_OPTS_APPEND

smoketest/compose/db-viewer.yml, smoketest/compose/db_k8s.yml, smoketest/k8s/db-viewer-deployment.yaml
=> test(db-viewer): upgrade pgadmin4 to 7.x

.gitmodules
Fixes: #125
related: [https://github.com/cryostatio/cryostat-web/pull/1158](https://github.com/cryostatio/cryostat-web/pull/1158)
2. *...*
=> ci(task): `cryostat-web` should commit and push changes to src/main/webui

smoketest/compose/db.yml
=> test(smoketest): correct database image

pom.xml
Related to #162 
Updates quarkus to the latest version available downstream
=> build(deps): bump quarkus to 3.2.6.Final

.github/workflows/dependent-issues.yml, .github/workflows/pr-ci.yaml
=> chore(ci): update ci workflow

src/test/java/itest/ClientAssetsIT.java
Forward-port of https://github.com/cryostatio/cryostat/pull/1830
=> test(client-assets): update test for relative app bundle location

smoketest/compose/s3-cloudserver.yml, smoketest/compose/s3-localstack.yml, smoketest/compose/s3-minio.yml, smoketest/compose/s3-seaweed.yml
Fixes: #266
See #241 (partial revert)
1. `./smoketest.bash`
2. Go to Recordings
3. Select Cryostat `localhost:0` as the target
4. Try to download one of the active recordings
=> test(smoketest): re-add environment variables for presigned downloads secrets

.github/workflows/ci-code-analysis.yml, .github/workflows/pr-ci.yaml, .github/workflows/push-ci.yaml, pom.xml
Related to https://github.com/cryostatio/cryostat-core/issues/92
=> build(cryostat-core): use -core from Maven Central

.github/workflows/pr-ci.yaml
Related to #100
Related to #123
Related to #179
2. *...*
=> ci(test): include JDK version in PR comment

src/main/java/io/cryostat/Producers.java
Related to https://github.com/cryostatio/cryostat-reports/pull/199
Depends on https://github.com/cryostatio/cryostat-core/pull/336
2. *...*
=> chore(automatedanalysis): use independent singlethreadexecutor if running on single CPU

src/main/java/io/cryostat/graphql/ActiveRecordings.java, src/main/java/io/cryostat/graphql/ArchivedRecordings.java, src/main/java/io/cryostat/graphql/RecordingLinks.java, src/main/java/io/cryostat/graphql/TargetNodes.java
=> feat(graphql): implement features to support dashboard automated analysis card

schema/openapi.yaml
=> fix(schema): update schema for current main

.github/workflows/pr-ci.yaml, schema/schema.graphql, schema/update.bash
Fixes: #333
See #334 
2. *...*
=> ci(schema): enable and check in graphql schema

.github/workflows/pr-ci.yaml
=> ci(schema): add pr-write permissions for comments

src/main/java/io/cryostat/discovery/Discovery.java, src/main/java/io/cryostat/events/S3TemplateService.java, src/main/java/io/cryostat/events/TargetTemplateService.java, src/main/java/io/cryostat/recordings/ActiveRecording.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/reports/ReportsServiceImpl.java, src/main/java/io/cryostat/reports/StorageCachingReportsService.java, src/main/java/io/cryostat/targets/TargetConnectionManager.java
=> chore(quarkus): remove improper uses of blocking annotation

pom.xml, src/assembly/quarkus-app.xml
Fixes: #379
* Adds a profile that, when enabled, produces a tarball of the quarkus-app build directory.
* Helpful for downstream builds
1. `mvn -Pdist package`
=> build(assembly): add profile to build assembly

.github/workflows/push-ci.yaml
=> ci(arm): install qemu for cross-arch image builds

.github/workflows/push-ci.yaml
=> ci(arm): install qemu in correct workflow

.github/workflows/pr-ci.yaml
See #294
See https://github.com/cryostatio/cryostat3/pull/375#issuecomment-2067226380
2. *...*
=> ci(schema): enable GraphQL schema tracking

.github/workflows/pr-ci.yaml
=> ci(schema): fix GraphQL schema tracking

src/main/java/io/cryostat/jmcagent/JMCAgent.java
Related to https://github.com/cryostatio/cryostat-web/issues/1247
2. *...*
=> fix(jmcagent): correct probe insert/remove notification contents

src/main/java/io/cryostat/discovery/Discovery.java
Fixes: #413
* Fixes the value of the `INSIGHTS_SVC` key in the environment map.
* When Insights integration is enabled, this allows the Agent to send reports to Insights.
=> fix(insights): send proxy service URL to agent

.github/workflows/push-ci.yaml
See https://github.com/cryostatio/cryostat3/pull/427
See https://github.com/cryostatio/cryostat-reports/pull/234
2. *...*
=> ci(cron): publish weekly rebuilds

src/main/java/io/cryostat/Producers.java, src/main/java/io/cryostat/reports/StorageCachingReportsService.java, src/main/java/io/cryostat/ws/MessagingServer.java
=> fix(ws): implement periodic ping frame

README.md
=> docs(readme): remove k8s mention in README

src/main/java/io/cryostat/discovery/Discovery.java, src/main/java/io/cryostat/discovery/KubeApiDiscovery.java
Related to #467
See also https://github.com/cryostatio/cryostat3/pull/454
2. *...*
=> fix(discovery): mark plugin refresh job as Transactional

README.md
=> docs(readme): minor revisions

README.md
=> docs(container): add quay.io registry link to README

compose/sample-apps.yml
Related to https://github.com/cryostatio/cryostat-agent/issues/382
Depends on https://github.com/cryostatio/cryostat-agent/pull/383
2. *...*
=> test(smoketest): configure quarkus-test-agent to use newer auth properties

.github/workflows/push-ci.yaml, .mergify.yml, compose/cryostat.yml, compose/cryostat_docker.yml, compose/cryostat_k8s.yml, src/main/resources/application.properties
=> chore(release): prepare release branch

src/main/java/io/cryostat/StorageBuckets.java, src/main/java/io/cryostat/credentials/CredentialsFinder.java, src/main/java/io/cryostat/discovery/ContainerDiscovery.java, src/main/java/io/cryostat/discovery/DiscoveryPlugin.java, src/main/java/io/cryostat/discovery/JDPDiscovery.java, src/main/java/io/cryostat/discovery/KubeApiDiscovery.java, src/main/java/io/cryostat/events/Events.java, src/main/java/io/cryostat/events/S3TemplateService.java, src/main/java/io/cryostat/jmcagent/JMCAgent.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/recordings/Recordings.java, src/main/java/io/cryostat/rules/RuleService.java, src/main/java/io/cryostat/targets/Target.java, src/main/java/io/cryostat/targets/TargetConnectionManager.java, src/main/java/io/cryostat/ws/MessagingServer.java, src/test/java/io/cryostat/resources/LocalStackResource.java, src/test/java/itest/bases/StandardSelfTest.java
=> chore(logs): audit log levels

src/main/java/io/cryostat/rules/RuleService.java
=> fix(rules): add blocking annotation for rules error

README.md
=> docs(readme): update readme link for old repo

CONTRIBUTING.md, README.md, compose/cryostat.yml, compose/cryostat_docker.yml, compose/cryostat_k8s.yml, compose/db.yml, compose/no_proxy.yml, compose/servers.json, pom.xml, schema/openapi.yaml, src/main/docker/Dockerfile.jvm, src/main/resources/application.properties, src/test/java/itest/bases/StandardSelfTest.java
=> chore(rename): clean up references to cryostat3 name

README.md, compose/auth_proxy.yml, compose/cryostat.yml, compose/cryostat_docker.yml, compose/cryostat_k8s.yml, compose/jfr-datasource.yml, compose/reports.yml, compose/s3-cloudserver.yml, compose/s3-localstack.yml, compose/s3-minio.yml, compose/s3-seaweed.yml
Related to #292
Since #292 we no longer maintain upstream kompose-based smoketests, instead using the Operator or Helm Chart as we did with prior Cryostat versions.
=> test(smoketest): remove references to kompose

.github/workflows/push-ci.yaml, src/main/docker/Dockerfile.builder
- **ci(oci): update builder and runner image versions**
- **correct label**
- **add missing configs**
See #373
2. *...*
=> ci(oci): builder image fixups

src/main/docker/Dockerfile.builder
=> ci(oci): builder image base image version (#566)

.github/workflows/pr-ci.yaml
=> ci(schema): auto commit schema changes

.github/workflows/pr-ci.yaml, .github/workflows/push-ci.yaml, compose/s3-localstack.yml, pom.xml, src/test/java/io/cryostat/resources/LocalStackResource.java
See https://github.com/cryostatio/cryostat/pull/577#issuecomment-2245782283
2. *...*
=> ci(runner): use ubuntu 24.04 runner, ensure podman 4 from repo installed, use localstack:stable

.github/workflows/pr-ci.yaml
Part of: #577 
see [https://github.com/cryostatio/cryostat/actions/runs/10222382811/job/28286913639](https://github.com/cryostatio/cryostat/actions/runs/10222382811/job/28286913639)
2. *...*
=> ci(schema): update permissions for auto commit schema changes

src/main/java/io/cryostat/expressions/MatchExpressionEvaluator.java
Fixes: https://github.com/cryostatio/cryostat-web/issues/1320
Before:
After:
=> fix(matchexpr): expose 'isAgent' field for evaluation

pom.xml
See https://github.com/cryostatio/cryostat/pull/597
2. *...*
=> build(deps): bump org.apache.commons:commons-lang3 from 3.13.0 to 3.14.0

.github/workflows/pr-ci.yaml
=> feat(ci): verify bot commits for schema changes

compose/cryostat.yml
=> test(smoketest): correct startup JFR flags

src/main/java/io/cryostat/discovery/DiscoveryPlugin.java
Related to https://github.com/cryostatio/cryostat-agent/pull/508
Small logging changes, useful for troubleshooting registration failures.
2. *...*
=> chore(discovery): plugin registration logging

compose/sample_apps/spring-boot-2-7.yml, compose/sample_apps/spring-boot-3.yml
Related to https://github.com/cryostatio/test-applications/issues/19
Depends on https://github.com/cryostatio/test-applications/pull/22
2. *...*
=> test(smoketest): add Spring Boot test applications

compose/reports.yml
See https://github.com/cryostatio/cryostat-reports/pull/299
Enables docker/podman discovery of the reports sidecar in smoketest.
Adds one more target to work with, and in particular an additional one that supports the `quarkus-jfr` extension events.
2. *...*
=> test(smoketest): discover reports sidecar

pom.xml, src/test/java/itest/RulesPostJsonIT.java
=> chore(pom): remove quarkus-jfr extension

.gitmodules
=> fix(submodule): correct submodule branch ref

compose/sample_apps/clojure-kit.yml
Depends on https://github.com/cryostatio/test-applications/pull/33
Adds a non-Java, JVM language sample application.
Useful for showcasing that Cryostat can work just fine with any JVM-mode application, not only things written in Java language.
2. `./smoketest.bash -O -t clojure-kit`. If https://github.com/cryostatio/test-applications/pull/33 isn't merged yet, check out that PR and `cd clojure-kit ; TAGS=latest ARCHS=amd64 ./build.bash` to build it locally first.
3. Wait for everything to come up.
4. Open `https://localhost:8443` Cryostat UI and ensure that the clojure-kit application appears in Topology. It should …
=> test(smoketest): add clojure-kit sample

compose/sample_apps/quarkus-native.yml
See #803
Depends on https://github.com/cryostatio/test-applications/pull/34
See https://github.com/cryostatio/cryostat/pull/804
=> test(smoketest): add quarkus-native sample

pom.xml
=> test(skip): re-enable ability to skip unit tests

src/test/java/io/cryostat/jmcagent/JMCAgentProbesTest.java, src/test/java/io/cryostat/jmcagent/JMCAgentTemplatesTest.java
See https://github.com/cryostatio/cryostat-core/issues/450
2. *...*
=> test(jmc-agent): re-renable JMC Agent probe template test

.github/workflows/pr-ci.yaml, .github/workflows/push-ci.yaml
=> ci(testcontainers): ensure correct properties file content

.gitignore
=> chore(gitignore) ignore smoketest probes

compose/sample_apps/opensearch.yml, compose/sample_apps/quarkus-petclinic.yml
=> test(smoketest): use quay.io images for all sample apps

pom.xml
Fixes #737
See #790
Needs Quarkus 3.15.4 or 3.18+
2. *...*
=> chore(pom): add quarkus-jfr extension

src/main/java/io/cryostat/discovery/DiscoveryNode.java, src/main/java/io/cryostat/discovery/KubeApiDiscovery.java, src/main/java/io/cryostat/recordings/ActiveRecording.java, src/main/java/io/cryostat/rules/Rule.java, src/main/java/io/cryostat/targets/Target.java, src/main/resources/db/migration/V4.1.0__cryostat.sql
=> perf(sql): set up indices

src/main/java/io/cryostat/targets/TargetUpdateJob.java
=> chore(jvmid): lower log level for exception if target has been lost

src/main/java/io/cryostat/discovery/CustomDiscovery.java
Fixes #902
When attempting to delete a target by ID, check that the target is actually a member of the Custom Target realm. If it is not, respond with HTTP 400 Bad Request.
See #902
1. Check out and build `main`
2. `./smoketest.bash -O -t wildfly-28`
3. Use an HTTP client like HTTPie: `https --auth=user:pass DELETE :8443/api/v4/targets/1` (change `1` for each discovered target ID). Verify that the response is HTTP 204 No Content, which is the bug. Also verify that in the Cryostat UI, the target disappears from the target selector dropdown and/or Topology view.
4. Check out and build PR.
5. Repeat step 3, but now the DELETE requests …
=> fix(discovery): disallow deletion of non-custom targets

schema/openapi.yaml, src/main/java/io/cryostat/discovery/KubeApiDiscovery.java
Fixes #905
See #910
1. Set up k8s/OpenShift cluster
2. `oc project default` or the k8s equivalent
3. `$ helm install --set core.image.repository=quay.io/andrewazores/cryostat --set core.image.tag=k8s-disc-null-1 --set core.route.enabled=true --set core.discovery.kubernetes.enabled=true cryostat ./charts/cryostat`, or build and use your own image
4. Deploy a discoverable target application in the `default` namespace alongside Cryostat, ex. using the Cryostat Operator `make sample_app`
5. Wait for everything …
=> fix(discovery): handle nullable object fields in k8s endpoints objects

pom.xml
See https://github.com/cryostatio/cryostat-core/pull/552
2. *...*
=> build(pom): pull snapshots from Maven Central Portal

.github/workflows/pr-ci.yaml, src/test/java/itest/AgentDiscoveryIT.java, src/test/java/itest/AgentTargetAnalysisIT.java
=> ci(agent): enable tests only in PR CI

compose/auth_proxy.yml, compose/sample_apps/quarkus-cryostat-agent.yml, pom.xml, schema/openapi.yaml, schema/update.bash, src/main/java/io/cryostat/ObjectMapperCustomization.java, src/main/java/io/cryostat/Producers.java, src/main/java/io/cryostat/util/SemVer.java, src/main/resources/application.properties, src/test/java/io/cryostat/ApiListingTest.java, src/test/java/io/cryostat/discovery/DiscoveryPluginTest.java, src/test/java/io/cryostat/graphql/GraphQlReportsTest.java, src/test/java/io/cryostat/reports/AnalysisReportAggregatorTest.java, src/test/java/io/cryostat/reports/ReportsTest.java, src/test/java/io/cryostat/util/SemVerTest.java, src/test/java/itest/ReportGenerationTest.java, src/test/java/itest/SnapshotTest.java, src/test/java/itest/TargetRecordingPatchTest.java
Related to #1014
Fixes #947
2. *...*
=> chore(quarkus): upgrade to 3.25

pom.xml
=> chore(hibernate): sync hibernate-jfr version with Quarkus hibernate

src/main/java/io/cryostat/rules/Rule.java, src/test/java/io/cryostat/rules/RulesTest.java
Related to https://github.com/cryostatio/cryostat-web/issues/1789
=> fix(rules): set Automated Rule description to empty string if null

pom.xml
=> chore(quarkus): upgrade to 3.27 LTS
