cryostatio/cryostat

src/main/resources/application-dev.properties, src/main/resources/application-test.properties, src/main/resources/application.properties
Related to #73 
This disables all discovery mechanisms in production unless explicitly turned on.
> I would prefer to keep all the builtin discoveries toggled off by default in production builds, so each one is an opt-in feature specified when the Cryostat container is deployed. That's the opposite of previous Cryostat versions where everything is on by default and things need to be turned off either all at once or by listing out only the ones to turn on, which made some sense with how discovery used to work but I don't think necessarily makes sense anymore when there are multiple built-in options that can all be enabled in parallel.
See https://github.com/cryostatio/cryostat3/pull/26#discussion_r1242592780
I realized I misread the comment when porting the docker discovery: …
=> fix(properties): disable podman discovery in production by default

.github/workflows/ci.yaml
Fixes #99 
The `PATH` environment variable is not persisted (previously) with the `export` syntax. This must be done via `GITHUB_ENV`.
=> ci(build-test): persist PATH modifications with GITHUB_ENV

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/labeler.yml, .github/pull_request_template.md, .github/release-drafter.yml, .github/workflows/check-labels.yml, .github/workflows/ci-code-analysis.yml, .github/workflows/ci.yaml, .github/workflows/dependent-issues.yml, .github/workflows/labeler.yml, .github/workflows/linked-issue.yml, .github/workflows/pr-request-review.yml, .github/workflows/release-drafter.yml, .github/workflows/semantic-pr.yml, .github/workflows/verify-semantic-pull-request.yml, .mergify.yml, CONTRIBUTING.md, README.md, pom.xml
Based on: #22 
Added similar workflows  set of CI configurations as the previous cryostat project.
=> feat(ci): workflows added

CONTRIBUTING.md
Related: #112 
This is to add the missing images on `CONTRIBUTING.md` file
To give the contributor a clear image sample guide of the pages they will navigate
=> feat(ci): updated to take compare fork image sample

.github/dependabot.yml
Fixes: #118 
Dependabot should not be requesting review from both maintainers and reviewers teams. With this change only maintainers should be requested
Bug reported by @andrewazores: Dependabot PRs end up requesting review from both maintainers and reviewers teams.
2. *...*
=> ci(dependabot): remove reviewers config

src/main/java/io/cryostat/discovery/ContainerDiscovery.java, src/main/java/io/cryostat/discovery/DiscoveryNode.java, src/main/java/io/cryostat/discovery/DiscoveryPlugin.java, src/main/java/io/cryostat/events/SerializableEventTypeInfo.java, src/main/java/io/cryostat/expressions/MatchExpression.java, src/main/java/io/cryostat/expressions/MatchExpressionEvaluator.java, src/main/java/io/cryostat/recordings/EventOptionsBuilder.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/recordings/Recordings.java, src/main/java/io/cryostat/rules/Rule.java, src/main/java/io/cryostat/rules/RuleService.java, src/main/java/io/cryostat/targets/Target.java
=> chore(spotbugs): resolve spotbugs warnings

smoketest/compose/s3-minio.yml, smoketest/k8s/s3-deployment.yaml
Fixes: #137
Based on #131
Depends on #131
=> test(smoketest): update minio healthcheck to not require 'curl' in container

smoketest.bash, smoketest/compose/db-viewer.yml, smoketest/compose/jfr-datasource.yml, smoketest/compose/s3-localstack.yml, smoketest/compose/s3-minio.yml, smoketest/compose/sample-apps.yml
Related to #64
To test:
```bash
$ ./smoketest.bash -h
$ ./smoketest.bash -b
$ ./smoketest.bash -Xgtb
```
etc.
=> test(smoketest): open services in browser tabs when ready

.github/workflows/push-ci.yaml
Related to #144
https://github.com/cryostatio/cryostat3/actions/runs/6791664907/job/18463577147
I believe this failed because of the curly brace syntax. In my fork this was commented out to make sure it progressed to the "push to quay.io" stage and then failed as expected. Uncommenting this condition resulted in the JDK 21 build attempting to build the multiarch manifest image when it should have skipped that step.
=> ci(image): correct expression condition syntax

src/main/java/io/cryostat/recordings/Recordings.java, src/test/java/itest/UploadRecordingTest.java, src/test/java/itest/bases/StandardSelfTest.java
Related to #42
*Created new methods to handle the redirects to new V3 endpoints for the UploadRecordingTest*
Notes: It will fail during the create recording ("/api/v1/targets/%s/recordings") as it is expecting 201 and it is currently is returning 200 (updated Recordings to return 201) 
The original test to delete recording was expecting 200 code, but I think that the current 204 makes more sense. 
*vertx does not follow redirects for non GET and HEAP methods*
*mvn package*
=> test(itest): updated UploadRecordingTest to handle the redirects to V3 endpoints

smoketest/compose/cryostat.yml, smoketest/compose/cryostat_docker.yml, smoketest/compose/cryostat_k8s.yml, smoketest/k8s/cryostat-deployment.yaml, smoketest/k8s/smoketest.bash
=> test(smoketest): use updated cryostat3 container image tag

.github/workflows/pr-ci.yaml
Fixes: #123 
Depends on #151
2. *...*
=> ci(port): `/build_test` and related CI commands

README.md, src/test/java/itest/UploadRecordingTest.java, src/test/java/itest/bases/StandardSelfTest.java, src/test/java/itest/util/Utils.java
Related to #150
Refactors redirect handling utility methods into a WebClient extension
Slight clean up for encapsulation and clarify between what is a base webclient capability versus what is an extension for our integration tests only
=> test(redirects): refactor redirect handling

src/main/java/io/cryostat/Health.java
Port of https://github.com/cryostatio/cryostat/pull/1779
=> fix(liveness): execute on worker pool

smoketest.bash, smoketest/compose/s3-cloudserver.yml, smoketest/compose/s3-localstack.yml, smoketest/compose/s3-minio.yml, smoketest/compose/s3-seaweed.yml
Related to #67
To test:
```bash
$ USE_USERHOSTS=false ./smoketest.bash -bs cloudserver
$ USE_USERHOSTS=false ./smoketest.bash -bs seaweed
$ USE_USERHOSTS=false ./smoketest.bash -bs localstack
$ USE_USERHOSTS=false ./smoketest.bash -bs minio
```
All four of these should spin up and result in a working deployment with the same basic Cryostat functionalities. Minio will additionally open its admin console/file explorer.
=> test(smoketest): add additional s3 impl options

pom.xml, src/main/java/io/cryostat/recordings/Recordings.java, src/main/java/io/cryostat/reports/Reports.java, src/main/resources/application-test.properties, src/test/java/io/cryostat/resources/GrafanaResource.java, src/test/java/io/cryostat/resources/JFRDatasourceResource.java, src/test/java/io/cryostat/resources/LocalStackResource.java, src/test/java/itest/NonExistentTargetIT.java, src/test/java/itest/NoopAuthV2IT.java, src/test/java/itest/NotificationsUrlIT.java, src/test/java/itest/RecordingWorkflowTest.java, src/test/java/itest/bases/StandardSelfTest.java, src/test/java/itest/util/Utils.java
Related to: #42 
*Updated NonExistentTargetIT, NoopAuthV2IT, NotificationsUrlIT, changed RecordingWorkflowIT to RecordingWorkflowTest*
Note: The RecordingWorkflowTest will fail because the report is returning in json format, but it is expecting html. 
*Enable the tests*
*mvn package*
=> test(itest): updated the tests and created a localstack resource

src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/recordings/Recordings.java
Cleans up some archived recording metadata handling and ensures that the `jvmId` and `connectUrl` labels get applied.
Related to #62 
To test:
1. `./mvnw clean verify`
2. `./smoketest.bash -OXtb`, wait for everything to come up
3. Select a target ex. `Podman > service:jmx:rmi:///jndi/rmi://sample-app:9093/jmxrmi`
4. Recordings > Create > create a recording
5. Wait a few seconds, then archive that recording
6. Go to Archives > All Archives > expand the target
7. Check that the archived recording is present and has the expected labels
Before:
(notice that the `connectUrl` label is actually the `jvmId`, and there is no `jvmId` label)
After:
=> fix(archives): correct recording metadata in S3 tags

pom.xml, src/main/java/io/cryostat/V2Response.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/recordings/Recordings.java, src/test/java/itest/SnapshotIT.java, src/test/java/itest/SnapshotTest.java, src/test/java/itest/TargetEventsGetIT.java, src/test/java/itest/TargetEventsGetTest.java, src/test/java/itest/bases/StandardSelfTest.java, src/test/java/itest/util/Utils.java
Fixes: #177
Reimplements JFR snapshot API v1 and v2, plus adds v3. These are all quite similar, just the response body format and status codes vary slightly.
1. `./mvnw clean verify ; podman image prune -f`
2. `./smoketest.bash -OXtb` and wait for things to come up
3. Select a target
4. Recordings > Create > Snapshot > Create . This should fail and display a warning notification message about there being no source data to snapshot.
5. Recordings > Create > Custom > create a new recording
6. Repeat step 4, this time it should succeed.
=> feat(recordings): implement JFR snapshot

src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/recordings/Recordings.java
Fixes: #175
Related to https://github.com/cryostatio/cryostat/pull/1692 - -web is shared between the 2.4 and 3.0 server versions, and 2.4/-web expect this API change but 3.0 did not yet.
=> fix(archives): cannot delete archived recording

smoketest.bash, smoketest/compose/auth_proxy.yml, smoketest/compose/cryostat-grafana.yml, smoketest/compose/cryostat.yml, smoketest/compose/cryostat_docker.yml, smoketest/compose/cryostat_k8s.yml, smoketest/compose/db-viewer.yml, smoketest/compose/db.yml, smoketest/compose/db_k8s.yml, smoketest/compose/jfr-datasource.yml, smoketest/compose/s3-cloudserver.yml, smoketest/compose/s3-localstack.yml, smoketest/compose/s3-minio.yml, smoketest/compose/s3-seaweed.yml, smoketest/compose/sample-apps.yml
Related to #64
Allows override of smoketest container images using env vars.
Useful for spinning up tests using different versions of various containers to test integration, ex. `/build_test` images.
1. `./mvnw clean package ; podman tag quay.io/cryostat/cryostat:3.0.0-snapshot quay.io/$myusername/cryostat:test-1 ; podman push quay.io/$myusername/cryostat:test-1` - make sure you replace `$myusername`, and that your `quay.io` repository is public
2. `CRYOSTAT_IMAGE=quay.io/$myusername/cryostat:test-1 bash smoketest.bash -O`
3. `podman ps -a` - the smoketest should be running your `test-1` container.
=> test(smoketest): allow overriding container images by env var

smoketest.bash, smoketest/compose/auth_proxy.yml, smoketest/compose/cryostat.yml, smoketest/compose/no_proxy.yml, smoketest/compose/sample-apps.yml
Related to #208
Related to #64
This adds a `-p` switch to `smoketest.bash` for disabling the `oauth2-proxy` configuration.
Developers can now choose whether to have Cryostat deployed directly with no authentication (add `-p`) or deployed with the `oauth2-proxy` providing `Basic` authentication (without `-p`). In either case, the exposed port is now `8080` rather than `8181`. 
1. `bash smoketest.bash -Xgt` to run the smoketest with the `oauth2-proxy` enabled. This should look the same as running it on current `main`. `podman ps` to inspect the running containers - there should be an auth proxy. Open a private browsing window and go …
=> test(smoketest): auth proxy is optional

smoketest.bash, smoketest/compose/auth_proxy_alpha_config.yaml, smoketest/compose/cryostat-grafana.yml, smoketest/compose/grafana_no_proxy.yml
Related to #208
Related to #64
Places the Grafana dashboard container behind the OAuth proxy the same way that the Cryostat server is. The Grafana dashboard is hosted at the subpath `/grafana/`, and the container is configured to know about this subpath. The Cryostat server is configured to direct clients to that path when the "View in Grafana..." UI control is clicked.
This allows both the Cryostat server and Grafana server to be deployed with no direct authentication or authorization of their own. Instead, both are only reachable by going through the proxy, which handles all user authentication and authorization before traffic can …
=> test(smoketest): place Grafana dashboard behind oauth proxy

smoketest/compose/s3-cloudserver.yml, smoketest/compose/s3-localstack.yml, smoketest/compose/s3-minio.yml, smoketest/compose/s3-seaweed.yml
Related to https://github.com/cryostatio/cryostat-web/pull/1206
Opens the smoketest compose ports to requests from the host.
This is required for host requests (ex. browser client on the host) to be able to make requests to the object storage (S3) container, which would be the case when the client tries to download a recording for example.
1. Build cryostat3 with https://github.com/cryostatio/cryostat-web/pull/1206
2. `./smoketest.bash -O`, open `localhost:8080` in a browser
3. Go to Recordings, select `localhost:0` target, then try to download an active recording.
4. Archive an active recording, go to Archives > All Archives, and …
=> test(smoketest): expose storage API ports externally

pom.xml, smoketest.bash, smoketest/compose/auth_proxy_alpha_config.yaml, smoketest/compose/s3-cloudserver.yml, smoketest/compose/s3-localstack.yml, smoketest/compose/s3-minio.yml, smoketest/compose/s3-seaweed.yml, smoketest/compose/s3_no_proxy.yml, smoketest/compose/seaweed_cfg.json, src/main/java/io/cryostat/ConfigProperties.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/recordings/Recordings.java, src/main/resources/application.properties
Based on #235
Related to #2
Adds optional configuration `storage-ext.url`, similar to existing `grafana-dashboard-ext.url`.
Cryostat uses this URL to determine the externally-facing URL where the object storage provider (S3 instance) can be reached by requesting clients, since Cryostat is likely to use an internal URL to communicate with the storage provider, but should tell clients how to download files from the object store using an externally routable URL.
1. `./mvnw clean package ; podman image prune -f`
2. `./smoketest.bash -O`
3. `http -v --follow --auth=user:pass :8080/api/v3/activedownload/1` to attempt downloading an active …
=> feat(recordings): object storage URL may be different interally vs externally

.github/workflows/pr-ci.yaml, .github/workflows/push-ci.yaml, README.md
Fixes: #221
Update configuration to allow `ryuk` container to run, which is responsible for cleaning up leftover containers (like cryostat-db or other postgres) after test runs.
1. Make the environment setup changes as listed in the updated `README`
2. `./mvnw clean verify ; podman image prune -f ; podman ps -a`. There may be some containers running at this point:
```
CONTAINER ID  IMAGE                                COMMAND               CREATED             STATUS             PORTS                    NAMES
56b3e0c3d6b6  docker.io/testcontainers/ryuk:0.5.1  /bin/ryuk             About a minute ago  Up About a minute …
```
=> ci(db): clean up database container after test run

src/main/java/io/cryostat/rules/RuleService.java, src/main/java/io/cryostat/rules/ScheduledArchiveJob.java
Fixes: #245
Annotate method with `@Transactional` to ensure the database cursor/connection is not prematurely closed.
See #245
See #245
Also try:
```json
{
"name": "test",
"description": "",
"matchExpression": "!target.connectUrl.startsWith('http')",
"eventSpecifier": "template=Profiling,type=TARGET",
"archivalPeriodSeconds": 15,
"initialDelaySeconds": 0,
"preservedArchives": 3,
"maxAgeSeconds": 0,
"maxSizeBytes": 10485760,
"enabled": false,
"recordingName": "auto_test"
}
```
Upload this rule definition and enable it. Recordings should be started within a few seconds, and then every 15 seconds afterward should be archived, and once …
=> fix(rules): rule application occurs within DB transaction to ensure cursor is not closed prematurely

smoketest/compose/cryostat.yml
Related to #28
Adds a startup profiling flight recording to Cryostat itself in smoketesting.
We can/should use this recording every now and then to check Cryostat's own startup performance and look for ways to optimize it so that the startup is faster and leaner.
1. `./smoketest.bash`
2. Open web UI on `http://localhost:8080`
3. Select `localhost:0` target, go to Recordings > Active Recordings and verify that the `startup` recording is present
=> perf(startup): enable startup profiling recording

src/main/java/io/cryostat/expressions/MatchExpressionEvaluator.java, src/main/resources/application.properties
Fixes: #248
1. `./mvnw -Dtest=RulesTest clean test` and check that the exception is not logged
=> fix(matchexpr): correct invalidation logic

smoketest/compose/cryostat.yml, src/main/java/io/cryostat/ConfigProperties.java, src/main/java/io/cryostat/discovery/ContainerDiscovery.java, src/main/resources/application.properties
Fixes: #250
1. `./mvnw clean verify ; podman image prune -f`
2. `./smoketest.bash -O` and look for messages like `ERROR: io.cryostat.discovery.DockerDiscovery_Subclass enabled but socket /var/run/docker.sock is not accessible!` shortly after startup. The repeated log messages like in #250 should no longer appear. May be easier via `podman logs compose_cryostat_1` rather than the interleaved smoketest logs from all services.
```
Jan 22, 2024 3:37:08 PM io.cryostat.discovery.ContainerDiscovery onStart
ERROR: io.cryostat.discovery.DockerDiscovery_Subclass enabled but socket /var/run/docker.sock is not accessible!
Jan 22, 2024 3:37:08 …
```
=> fix(discovery): check container discovery domain socket readability before start

src/main/java/io/cryostat/credentials/Credential.java, src/main/java/io/cryostat/discovery/Discovery.java, src/main/java/io/cryostat/discovery/DiscoveryNode.java, src/main/java/io/cryostat/discovery/DiscoveryPlugin.java, src/main/java/io/cryostat/recordings/ActiveRecording.java, src/main/java/io/cryostat/rules/Rule.java, src/main/java/io/cryostat/rules/Rules.java, src/main/java/io/cryostat/targets/Target.java
Fixes: #256
Fixes #259
1. These `NotNull`/`NotBlank`/etc. changes should be mostly invisible in normal operation, since the UI and the API layer already perform checks and validations on these things so that nice UI messages can be displayed to the user as hints before submitting requests, or so that the server can return informative error messages on bad requests that do come through. Applying these checks at the persistence layer is the last line of defense to ensure that invalid data is not entered into the database.
2. The other `@JsonProperty` etc. changes ensure that particular fields do not get read or written when they …
=> chore(db): apply active record validation constraints

src/main/java/io/cryostat/targets/Target.java
Fixes: #268 
Since the alias is only used as a human-friendly label, it should be OK for these to be non-unique.
mentioned by @andrewazores [here](https://github.com/cryostatio/cryostat3/issues/268#issue-2098926923)
2. *...*
=> fix(Target): should accept non-unique aliases

smoketest/compose/reports.yml
Related to #267
Adds a simple HTTP healthcheck to the reports container, similar to what other smoketest containers already have
Allows smoketest harness to properly determine if -reports container has started up and restart it if necessary
=> test(smoketest): add healthcheck to -reports container

src/main/java/io/cryostat/ExceptionMappers.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/rules/Rules.java, src/main/java/io/cryostat/util/EntityExistsException.java
Related to https://github.com/cryostatio/cryostat-web/pull/1192
=> fix(notifications): More descriptive notifications

src/main/java/io/cryostat/ConfigProperties.java, src/main/java/io/cryostat/recordings/Recordings.java, src/main/resources/application.properties
Related to #284
Provides an alternative recording file download mechanism. Rather than creating an S3 presigned GET request URL and redirecting the client to that URL, Cryostat simply uses its own credentials to perform a standard GET request to S3, acting as a network pipe or proxy between the client and S3. This is more similar to the classic Cryostat 2.x implementation where Cryostat read archived recording files directly from the filesystem and served the client these bytes directly (as opposed to delegating to another server like the S3 container).
Similarly, the existing implementation for downloading active recordings works …
=> feat(download): implement download piping as default rather than presigned URLs

smoketest.bash, src/main/java/io/cryostat/ExceptionMappers.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/recordings/Recordings.java
Related to #2
Implements endpoints for "View in Grafana" feature upon archived recordings.
Previously, 3.0 only supported "View in Grafana" on active recordings.
2. Find or start an active running recording
3. Archive the recording, go to Archives view
4. Find the archived recording and "View in Grafana". Verify that the Grafana dashboard appears and has sensible data content.
=> feat(grafana): implement endpoint for 'view in grafana' of archived recordings

.github/dependabot.yml
=> ci(dependabot): remove config for GH mvn pkgs

src/main/java/io/cryostat/graphql/EnvironmentNodeGraphQL.java, src/main/java/io/cryostat/graphql/EnvironmentNodes.java
Based on: #294 
1. *Run CRYOSTAT_IMAGE=quay.io... bash smoketest.bash -O...*
2. `$ http --follow -v --auth=user:pass :8080/api/v3/graphql/schema.graphql` and ensure new schema contains top-level query and subqueries.
3. ` http --follow -v --auth=user:pass :8080/api/v2.2/graphql query='query { environmentNodes(filter: { nodeType: "Realm" }) { id name nodeType labels { key value } children { id name nodeType labels { key value } } } }'` change the filter to filter by name i.e ` http --follow -v …
=> feat(graphql): add top-level query for environmentNodes

src/main/java/io/cryostat/ObjectMapperCustomization.java, src/main/java/io/cryostat/graphql/RootNode.java, src/main/java/io/cryostat/graphql/TargetNodes.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/recordings/Recordings.java, src/main/java/io/cryostat/rules/RuleService.java, src/main/java/io/cryostat/ws/MessagingServer.java, src/main/resources/application.properties, src/test/java/itest/CustomTargetsTest.java
Based on https://github.com/cryostatio/cryostat3/pull/294
Depends on https://github.com/cryostatio/cryostat-core/pull/357
Depends on https://github.com/cryostatio/cryostat-core/pull/358
Depends on https://github.com/cryostatio/cryostat3/pull/310
2. `$ http --follow -v --auth=user:pass :8080/api/v3/graphql/schema.graphql` and ensure new schema contains top-level query and subqueries
3. Open web UI, select `localhost:0` target, archive both recordings. …
=> feat(graphql): add top-level query for targetNodes

src/main/java/io/cryostat/recordings/ActiveRecording.java, src/main/java/io/cryostat/recordings/Recordings.java
Related to #2
Depends on https://github.com/cryostatio/cryostat-web/pull/1221
1. Inserts the correct archived recording filesize into the WebSocket notification emitted when recordings are uploaded into archival storage
2. Corrects handling of archives to allow null JVM IDs, which is the case for client uploads
3. Corrects handling of archived recording deletion to accept `"uploads"` as a pseudo-"JVM ID", since that is how they are stored when uploaded
2. *...*
=> fix(archives): accept and delete recording uploads, emit event with correct size

src/main/java/io/cryostat/JsonRequestFilter.java, src/main/java/io/cryostat/discovery/CustomDiscovery.java, src/test/java/io/cryostat/JsonRequestFilterTest.java
Fixes: #278 
Server should validates the request payload and ensures that the id field is not specified. If fails validation, server responds with a 400/409 status before it even gets to the database.
Mentioned by  @andrewazores [Link](https://github.com/cryostatio/cryostat3/issues/278#issue-2121313813)
2. *...*
=> fix(server): should validate request payload: ensure id is not specified

src/main/java/io/cryostat/ExceptionMappers.java, src/main/java/io/cryostat/StorageBuckets.java, src/main/java/io/cryostat/events/S3TemplateService.java, src/main/java/io/cryostat/recordings/Recordings.java, src/main/java/io/cryostat/reports/Reports.java
=> chore(storage): refactor bucket check/create on startup

src/main/java/io/cryostat/JsonRequestFilter.java, src/test/java/io/cryostat/JsonRequestFilterTest.java
Related to #291
This is a partial cherry-pick of a patch included in #294. This fixes the current breakage on `main` where discovery plugins (ex. Cryostat Agents) are unable to register.
=> fix(id-filter): allow JSON 'id' key on particular endpoints only

src/main/java/io/cryostat/JsonRequestFilter.java, src/main/java/io/cryostat/targets/Target.java, src/main/java/io/cryostat/targets/Targets.java
Related to #2
Related to #71
Depends on #337
Cryostat 3 tolerates connection failures when attempting to determine newly discovered targets' JVM IDs. When new Credentials are added, Cryostat looks in the database for any targets with null JVM IDs (signifying the initial connection failure), checks if the new credential matches the target, and then re-attempts to determine the JVM hash ID and persist this update to the database.
Prior to this change, Cryostat 3 would always try to connect to newly discovered JVMs to determine their hash IDs. If this connection attempt failed for any reason then the discovery would be ignored and the …
=> fix(jmxauth): tolerate JMX auth failures at discovery, re-attempt if new matching Credentials added

src/main/java/io/cryostat/JsonRequestFilter.java
=> fix(matchexpressions): correct endpoint case for JSON ID request filter

src/main/java/io/cryostat/rules/ScheduledArchiveJob.java
Fixes: #357
Depends on #356
2. *...*
=> fix(rules): ensure archived recordings are sorted by age before pruning

src/main/java/io/cryostat/security/Auth.java
Related to #365
Depends on https://github.com/cryostatio/cryostat-web/pull/1236
When clicking the "logout" button in the application masthead, the web-client sends a request to the Cryostat server at `/api/v2.1/logout`. The current implementation just treats this as a no-op and returns HTTP 204. This new implementation responds with a redirect instructing the client to go to `/oauth2/sign_out`, which triggers the logout flow of the auth proxy.
Re-enables the ability for the user to log out.
1. Check out this PR
2. `./mvnw clean package ; podman image prune -f ; ./smoketest.bash -O`
3. Open UI, log in with `user:pass`, go to UI. Then …
=> fix(oauth): enable signout redirect

src/main/java/io/cryostat/ExceptionMappers.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/targets/TargetConnectionManager.java, src/test/java/itest/TargetEventsGetTest.java
Fixes: #348
Adds exception handling to the TargetConnectionManager's internal `Uni` pipeline, to catch and transform particular types of connection exceptions into `HttpException` with the correct status codes that the previous API defined and which the UI expects.
This re-enables the ability for the UI to display the JMX auth and cert warning modals when attempting to connect to targets for which there are no correct stored credentials or which present an untrusted cert.
1. Check out and build PR, `smoketest.bash -Ot`
2. Select `9093` sample app, go to Events view. Templates and types should load.
3. Select `9094` sample app, go to …
=> fix(jmx): restore error codes for auth and TLS connection failures

src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/recordings/RecordingOptionsBuilderFactory.java, src/main/java/io/cryostat/recordings/RecordingOptionsCustomizerFactory.java, src/main/java/io/cryostat/recordings/Recordings.java, src/main/java/io/cryostat/recordings/RecordingsModule.java, src/main/java/io/cryostat/rules/RuleService.java
Fixes: #184
Refactors the `RecordingOptionsCustomizer` implementation so that there is an internal in-memory cache `Map<Target, RecordingOptionsCustomizer>`. This way, the `PATCH /api/v1/:connectUrl/recordingOptions` request can set recording options defaults (for the "advanced options" of `maxAge`/`maxSize`/`toDisk`) for each target. Cache entries are evicted if the target is lost. These settings are only held in-memory and not persisted.
Usually, clients do not actually set defaults on targets like this, instead simply setting these options on each recording in the same request as creating the recording. However, the API does …
=> fix(recordingOptions): scope customizers to each Target

src/main/java/io/cryostat/recordings/Recordings.java
Based on #315
Adds a missing endpoint. This implementation mirrors the other similar one in that it simply redirects the client to a new API endpoint.
This re-enables the "View in Grafana" action in the UI for the "Recordings > Archived" and "Archives > All Targets" views.
2. *...*
=> fix(grafana): add redirecting endpoint for archived recordings

pom.xml
Fixes: #369
Adds Maven build profiles for build arch (ex. amd64, arm64) and for including or excluding `epoll`. `epoll` is used for Unix domain sockets, which we use in `ContainerDiscovery` for Docker/Podman API discovery of potential target containers.
Since the Netty `epoll` is a native dependency, ie contains compiled code rather than Java bytecode, the correct architecture for this dependency must be selected at build time to match the architecture of the machine that the container will run upon. Before this PR the dependency is hardcoded to `amd64`, so container discovery cannot function on other architectures such as `arm64`. …
=> build(arch): use build arch profiles for native dependency classification

pom.xml
=> chore(pom): remove build.os property that breaks Dependabot scanning

compose/cryostat.yml, schema/openapi.yaml, smoketest.bash, src/main/docker/Dockerfile.jvm, src/main/docker/include/entrypoint.bash, src/main/docker/include/genpass.bash, src/main/docker/include/truststore-setup.bash, src/main/java/io/cryostat/ConfigProperties.java, src/main/java/io/cryostat/security/TrustStore.java, src/main/resources/application-dev.properties, src/main/resources/application.properties
Based on #329
Related to #2
Related to #71
Copies a simplified version of Cryostat 2.4's `entrypoint.bash` and `truststore-setup.sh` into the container build, sets up the container to initialize with the truststore copy and the entrypoint to copy in any additional user-supplied certificates into this truststore, before finally launching the server JVM.
This allows users (the ones who deploy Cryostat, not the ones who interact with the UI and API) to supply TLS certificates that their target applications present for JMX connections. This restores Cryostat 3's ability to connect to such JMX/TLS-enabled targets.
1. `mkdir truststore` …
=> feat(jmx): custom entrypoint to support copying TLS certs into truststore for JMX

src/main/java/io/cryostat/targets/Target.java
=> fix(discovery): do not require nonnull jvmIds for websocket notifications

schema/openapi.yaml, smoketest.bash, src/main/java/io/cryostat/ConfigProperties.java, src/main/java/io/cryostat/jmcagent/JMCAgent.java, src/main/java/io/cryostat/jmcagent/S3ProbeTemplateService.java, src/main/java/io/cryostat/jmcagent/SerializableProbeTemplateInfo.java, src/main/java/io/cryostat/targets/TargetConnectionManager.java, src/main/resources/application.properties
Fixes https://github.com/cryostatio/cryostat3/issues/14
Depends on https://github.com/cryostatio/cryostat-core/pull/373
Depends on https://github.com/cryostatio/cryostat3/pull/385
This PR re-implements the JMC Agent functionality for Cryostat 3.0.
I took inspiration from how the event templates system was rewritten for rewriting the probe template service. 
Opening as draft for the moment as it doesn't quite run properly yet and I still need to re add the notifications. There will likely need to be some cleanup done in core as well.
=> feat(jmcagent): JMC Agent Feature Parity

src/main/java/io/cryostat/expressions/MatchExpressions.java, src/main/java/io/cryostat/graphql/ActiveRecordings.java, src/main/java/io/cryostat/graphql/ArchivedRecordings.java, src/main/java/io/cryostat/graphql/EnvironmentNodes.java, src/main/java/io/cryostat/graphql/RootNode.java, src/main/java/io/cryostat/graphql/TargetNodes.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/recordings/Recordings.java, src/main/java/io/cryostat/reports/Reports.java, src/main/resources/application.properties
Fixes: #389
Based on #342
- ensures `Blocking` and `Transactional` annotations are applied correctly in GraphQL API entrypoints and HTTP API entrypoints
- disables GraphQL nonblocking support, improves performance but is more difficult to manage the concurrency - not worth gaining performance at the expense of correctness or reliability
- refactors some code using to ensure that database transactions occur on the calling thread where the transaction context is active, not on some delegated worker
2. *...*
=> fix(transaction): ensure transactions occur in correct context/thread

pom.xml, src/main/java/io/cryostat/discovery/ContainerDiscovery.java, src/main/java/io/cryostat/discovery/CustomDiscovery.java, src/main/java/io/cryostat/discovery/Discovery.java, src/main/java/io/cryostat/discovery/DiscoveryNode.java, src/main/java/io/cryostat/discovery/JDPDiscovery.java, src/main/java/io/cryostat/discovery/KubeApiDiscovery.java, src/main/java/io/cryostat/discovery/NodeType.java, src/main/java/io/cryostat/targets/Target.java, src/main/resources/application-dev.properties, src/main/resources/application-test.properties, src/main/resources/application.properties
Fixes: #238 
Port KubeDiscoveryAPI from v2 to v3.
See #238
Build the application and push to quay.io:
```bash
IMAGE_NAMESPACE=quay.io/thvo
./mvnw clean package -DskipTests=true && \
podman tag quay.io/cryostat/cryostat:3.0.0-snapshot ${IMAGE_NAMESPACE}/cryostat:3.0.0-snapshot && \
podman push ${IMAGE_NAMESPACE}/cryostat:3.0.0-snapshot
```
Install the application with Helm Chart (https://github.com/cryostatio/cryostat-helm/pull/128):
```bash
helm install cryostat3 ./charts/cryostat/ \
--set core.discovery.kubernetes.enabled=true \
--set core.discovery.kubernetes.namespaces="{default,myns,.}" \
--set …
```
=> feat(discovery): port kubeApi discovery to v3

.github/dependabot.yml
Related to: #363
Related to #364 
* Tells Dependabot to ignore major and minor versions of Quarkus dependencies.
* Makes it easier to pull in Quarkus bugfix releases
=> chore(deps): ignore major/minor Quarkus updates

src/main/java/io/cryostat/discovery/KubeApiDiscovery.java
Fixes: #416 
Null check for `EndpointPort.getName` and `EndpointPort.getPort`.
In cases, where the endpoint's port does have a name. It can fail with NullPointerException. See #416
=> fix(discovery): null check for compatible port name and number

src/main/java/io/cryostat/discovery/ContainerDiscovery.java, src/main/java/io/cryostat/targets/Target.java
Fixes: #412 
- Fetched (pod) discovery node from database if any when handling `FOUND` event.
- Fixed deletion fails when deleting pods (i.e. podman), thus causing new containers to be considered duplicate.
- Need a label to keep track of the container ID so that we just delete by container id instead of fetching for container information. In the case of `LOST` event, the query will return null -> NullPointerException.
- With this fix, deleting a pod now works fine. 
See #412 
```bash
podman pod create --replace --name cryostat-pod
podman run \
--name jmxquarkus \
--pod cryostat-pod \
--label io.cryostat.discovery="true" \
--label …
```
=> fix(discovery): fix duplicate pod nodes in container discovery

src/main/java/io/cryostat/security/TrustStore.java
=> fix(tls): return empty list if custom truststore dir is not accessible

src/main/java/io/cryostat/ws/MessagingServer.java, src/main/resources/application.properties
Related to https://github.com/cryostatio/cryostat3/pull/423
Simplifies the MessagingServer (WebSocket notifications) implementation to remove the explicit thread synchronization and message ordering.
Using the EventBus is simpler and less error-prone than manually using synchronization features like blocking queues. Error handling is also improved in this PR, so if sending a notification to any connected client fails then this failure will be logged.
2. Click around the UI performing actions and ensure notifications are still received
=> chore(ws): simplify messaging server

compose/db.yml, smoketest.bash, src/main/java/io/cryostat/discovery/ContainerDiscovery.java, src/main/java/io/cryostat/targets/Target.java
Related to #420 
- Update container event handler to check with persisted targets.
See https://github.com/cryostatio/cryostat3/pull/420#issuecomment-2079879609. This fixes the problem when cryostat is restarted, observed targets will cause duplicate key violation and removed targets remain in database (stale).
```
mvn clean package -DskipTests=true
CRYOSTAT_DISCOVERY_JDP_ENABLED=false bash smoketest.bash -O
```
=> fix(discovery): observed containers should be checked with persisted nodes

src/main/java/io/cryostat/discovery/KubeApiDiscovery.java
Related to #423 
-  `KubeAPIDiscovery` to handle endpoint discovery event separately. This allows the kubeAPI realm to be populated instead of being left empty due to a single error in 1 handling case.
- Lazily initialize `KubernetesClient`: When deployed in non-k8s environment previously, k8s client is also initialized and automatically looking for cluster config.
```
2024-05-02 23:33:00,991 DEBUG [io.fab.kub.cli.Config] (main) Trying to configure client from Kubernetes config...
2024-05-02 23:33:00,992 DEBUG [io.fab.kub.cli.Config] (main) Did not find Kubernetes config at: [/home/jboss/.kube/config]. Ignoring.
2024-05-02 …
```
=> fix(discovery): handle endpoint discovery events separately

src/main/java/io/cryostat/graphql/ActiveRecordings.java, src/main/java/io/cryostat/recordings/RecordingHelper.java
- fix(recording): fix NPE when starting a recording without specified template type
- fix(graphql): avoid ConcurrentModificationException
Fixes: #432
2. *...*
=> fix(graphql): avoid ConcurrentModificationException

compose/cryostat.yml, compose/db-viewer.yml, compose/sample-apps.yml, schema/openapi.yaml, src/main/java/io/cryostat/credentials/Credential.java, src/main/java/io/cryostat/credentials/Credentials.java, src/main/java/io/cryostat/discovery/CustomDiscovery.java, src/main/java/io/cryostat/discovery/Discovery.java, src/main/java/io/cryostat/discovery/DiscoveryNode.java, src/main/java/io/cryostat/discovery/DiscoveryPlugin.java, src/main/java/io/cryostat/discovery/JDPDiscovery.java, src/main/java/io/cryostat/discovery/KubeApiDiscovery.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/rules/RuleService.java, src/main/java/io/cryostat/rules/ScheduledArchiveJob.java, src/main/java/io/cryostat/targets/AgentClient.java, src/main/java/io/cryostat/targets/TargetConnectionManager.java
Fixes: #405
Fixes: #440
Removes useless instances of `Transactional` annotation and replaces them with `QuarkusTransaction.joiningExisting()` invocations where applicable.
Ensures operations actually occur in a transactional context as expected
2. Click around UI performing actions and ensure general functionality works as expected. Pay particular attention to Topology view/actions, Archives > All Targets, and Automated Rules, since these exercise things the most.
3. Create an automated rule like the one below and ensure that it correctly creates a new recording when enabled, …
=> fix(db): correct use of Transactional annotation

src/main/java/io/cryostat/discovery/JDPDiscovery.java
Related to #415 / #407
Fixes missed change correcting the eventbus publication address of JDP discovery messages.
JDP discovery works again.
2. `./smoketest.bash -Ot`
3. Go to Topology view and ensure JDP nodes are discovered
=> fix(discovery): JDP event bus broadcast to correct address

src/main/java/io/cryostat/Health.java, src/test/java/io/cryostat/HealthTest.java
Fixes: #450
Implements the correct reports generation healthcheck behaviour, matching the previous 2.x versions.
This is useful for diagnosing reports sidecar configuration and is also used by some automated tests.
2. `./smoketest.bash -O`, then in another terminal `http --auth=user:pass :8080/health`. Check that reports are not configured but are available.
2. `./smoketest.bash -Or`, then in another terminal `http --auth=user:pass :8080/health`. Check that reports are both configured and available.
3. Edit `compose/reports.yml` and change the `QUARKUS_REST_CLIENT_REPORTS_URL` to a different port number or …
=> fix(health): correctly check reports service health

src/main/java/io/cryostat/recordings/RecordingHelper.java
Fixes: #453 
see [https://github.com/cryostatio/cryostat3/issues/453](https://github.com/cryostatio/cryostat3/issues/453)
2. Go to Recordings
3. Create a 10 second recording with Archive on Stop option selected and wait for 10 seconds
4. See notification appears and table updated (recording is now in STOPPED state)
5. Go to Recordings > Archived Recordings, the archived recording should be available
=> fix(archive-on-stop): add missing @Transactional annotation on StopRecordingJob

src/main/java/io/cryostat/jmcagent/JMCAgent.java, src/main/java/io/cryostat/jmcagent/S3ProbeTemplateService.java, src/main/java/io/cryostat/jmcagent/SerializableProbeTemplateInfo.java
Fixes: https://github.com/cryostatio/cryostat-core/issues/297
Accounts for changes in core to rename the jmc agent classes and clean up the LocalProbeTemplateService
1. Add the JMC Agent to the cryostat image
2. Manually test the agent handlers/functionality
Depends on https://github.com/cryostatio/cryostat-core/pull/398
=> chore(jmacagent): Update JMC Agent handlers to account for core changes

src/main/java/io/cryostat/events/EventTemplates.java, src/main/java/io/cryostat/events/S3TemplateService.java, src/main/java/io/cryostat/events/TargetTemplateService.java, src/main/java/io/cryostat/targets/AgentJFRService.java
Fixes: https://github.com/cryostatio/cryostat-core/issues/300
Related To: https://github.com/cryostatio/cryostat-core/pull/389
Adjusts the S3TemplateService and API handlers to account for proposed changes to the TemplateService to avoid directly exposing the Document type.
The S3TemplateService still knows about the Document type and uses it since that's its' implementation, however it does not expose it to callers of getXML.
2. *...*
Tested with ./mvnw run:quarkus-dev and testing the event template functionality/starting …
=> chore(cleanup): Adjust for core changes to abstract away the Document type

schema/openapi.yaml, src/main/java/io/cryostat/credentials/CredentialCheck.java, src/main/java/io/cryostat/credentials/CredentialsTest.java, src/main/java/io/cryostat/targets/AgentClient.java, src/main/java/io/cryostat/targets/TargetConnectionManager.java
Fixes: #478
Related to #2
Reimplements the `/api/beta/credentials/{connectUrl}` endpoint. This is used on the Security > Store Credentials > List view for testing credentials against targets before actually storing the credential.
2. `./smoktest.bash -Ot`
3. Go to Security > Store Credentials
4. Enter a test credential with the match expression `true` and credentials `admin:adminpass123`
5. Click the List tab and click Test for each target
6. Verify that the credential is Valid for vertx-fib-demo targets with ports 9094 and 9095, Invalid for cryostat3:9091, and Not Applicable for all others
Before this PR, …
=> feat(credentials): add missing credentials test endpoint

.github/workflows/pr-ci.yaml, src/main/docker/include/cryostat.jfc, src/main/java/io/cryostat/events/TargetTemplateService.java, src/main/java/io/cryostat/expressions/MatchExpressionEvaluator.java, src/test/java/itest/CryostatTemplateIT.java
Fixes: #481
There was a bit of jumbled handling of an Optional in the implementation from #449, which resulted in an Optional that wrapped around another `Optional#toString()` call erroneously. The original Optional itself is the expected return, not its String form.
This got missed because the test doesn't run in CI. I think this is because of the Maven property to not build container images during CI. This probably made sense previously when there were no real tests to run and so building the container image as a throwaway was just a waste of CI time, but now there are integration tests to be run which do need the container image …
=> fix(template): correct return of String-encoded Optional

compose/cryostat.yml, compose/db.yml, compose/s3-cloudserver.yml, compose/s3-localstack.yml, compose/s3-minio.yml, compose/s3-none.yml, compose/s3-seaweed.yml, smoketest.bash
1. Cleans up some service dependency declarations to be placed in the correct files so that services are easier to mix and match.
2. Adds `s3-none.yml`, which is an intentionally stub-out of the S3 provider, pointing Cryostat at a nonexistent S3 service and not starting any S3 service. This would not be useful in normal circumstances but can be used to check Cryostat's behaviour if its S3 object storage goes offline or is otherwise unreachable.
2. `./smoketest.bash -O -s none`
3. This should hang for quite a while as Cryostat repeatedly tries to check for the storage buckets it expects, but is unable to resolve the …
=> test(smoketest): cleanup, add config to run without S3

src/main/java/io/cryostat/recordings/RecordingHelper.java
Fixes: #441
This change will update the Archived Recordings table with the correct data (i.e Name and Size), when Recordings are created and archived with `Automated Rules`.
Mentioned earlier by @andrewazores [https://github.com/cryostatio/cryostat3/issues/441](https://github.com/cryostatio/cryostat3/issues/441)
1. checkout on this PR and run smoketest. 
2. create an Automated Rule  -> `Automated Rules` -> `Create`
```{
"id": 1,
"name": "test",
"description": "",
"matchExpression": "target.connectUrl.contains('localhost:0')",
"eventSpecifier": "template=Profiling,type=TARGET",
"archivalPeriodSeconds": 10,
"initialDelaySeconds": 0, …
```
=> fix(Archived Recordings): Archived Recordings tables improperly react to "Recording Saved" notifications

compose/cryostat.yml, compose/reports.yml, src/main/java/io/cryostat/discovery/CustomDiscovery.java
Fixes: #487
See also cryostatio/cryostat-web#1262
- fixes transaction handling bug (see #415)
- include better/more informative/more understandable error messages in responses
- check for duplicate URL or duplicate target (same JVM ID) cases in connection test, not only at creation time
2. `./smoktest.bash -Otr`
3. Go to Custom Target creation form
4. Try to create various custom targets like `cryostat3:9091`, `localhost:0`, `sample-app-1:9093`, `jfr-datasource:11223`, `reports:11224`
=> fix(custom-targets): fix bug in transactions, handle more failure cases, include more helpful text with failure responses

src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/targets/AgentConnection.java, src/main/java/io/cryostat/targets/AgentJFRService.java
Fixes: #491
Depends on https://github.com/cryostatio/cryostat-core/pull/403
See #342
See https://github.com/cryostatio/cryostat-core/pull/389
Some recent patches to Cryostat and cryostat-core changed how event templates are handled. The current Cryostat `main` has a bug where custom event templates can be successfully uploaded to storage, listed, and downloaded back from storage, but when trying to use the template to create a new recording then the action fails. The root of the failure is that Cryostat tries to start the recording by asking the -core service implementation to start the recording using the custom event template, but …
=> fix(recordings): correctly retrieve custom event templates from S3 storage

src/main/java/io/cryostat/Health.java, src/main/java/io/cryostat/security/Auth.java, src/main/resources/application-dev.properties
- **chore(headers): clean up unused headers references**
- **fix(auth): use X-Forwarded-User header to populate username response**
Related to #489
If the `X-Forwarded-User` header is present in the request, use this to populate the `POST /api/v2.1/auth` response. This header may be provided to Cryostat by its auth proxy. If there is no such header (there is no proxy, or the proxy doesn't send this) then the empty string is used.
This may allow Cryostat to inform the client of the username that was provided to the auth proxy. In the case of the web-client this can be used to include the user's username in the application UI.
1. Not …
=> fix(auth): use X-Forwarded-User header to populate username response

.github/workflows/push-ci.yaml, .mergify.yml, compose/cryostat.yml, compose/cryostat_docker.yml, compose/cryostat_k8s.yml, pom.xml, schema/openapi.yaml, src/main/resources/application.properties
- **ci(tags): tag images as 'latest'**
- **test(smoketest): run 'latest' Cryostat image tag**
- **chore(release): enable mergify backport rule**
- **chore(release): update project to 4.0.0-SNAPSHOT, use -core 4.0.0-SNAPSHOT**
2. *...*
=> chore(release): prepare for 3.0.0 release

.github/workflows/push-ci.yaml
=> ci(tags): do not apply 'dev' or 'latest' tags to intermediate container builds

src/main/java/io/cryostat/discovery/Discovery.java, src/main/java/io/cryostat/targets/Target.java
Fixes: #495
Corrects a database query. Previously it queried with `find("id", (String) null)`, which generates a SQL query like `select from Target where jvmId = null` and returns no results, even when there are targets with null JVM IDs. The new query is slightly different: `select from Target where jvmId is null`, with the **is null** being the significant difference. With this the database query correctly comes back with the targets with a null JVM ID.
https://stackoverflow.com/questions/9581745/sql-is-null-and-null
This fixes the Target persist hook that is responsible for checking if newly stored credentials apply to targets, …
=> fix(jvmId): correct query for Targets with null jvmId

compose/cryostat-grafana.yml, compose/s3-cloudserver.yml, compose/s3-localstack.yml, compose/s3-minio.yml, compose/s3-seaweed.yml, smoketest.bash
See https://github.com/cryostatio/cryostat-operator/pull/874
2. *...*
=> test(smoketest): use relative ext redirect URLs

src/main/java/io/cryostat/expressions/MatchExpressionEvaluator.java, src/main/java/io/cryostat/expressions/MatchExpressions.java
- **fix(matchexpr): invalidate expression cache on Target event**
- **fix(matchexpr): correct lookup of Target objects for match expression testing**
Fixes #511
The most important change is in `MatchExpressions.java`. The backend should not trust the client to provide the list of whole `Target` objects to evalute match expressions against. This endpoint should really just take a list of target database IDs that the client wants to test with the provided match expression, but it is late to make such a change now. With this patch the server picks only the `connectUrl` from each of the client's provided targets, then looks up each …
=> fix(matchexpr): correct lookup of Target objects for match expression testing

src/main/java/io/cryostat/expressions/MatchExpressionEvaluator.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/recordings/Recordings.java, src/main/java/io/cryostat/rules/RuleService.java, src/main/java/io/cryostat/rules/ScheduledArchiveJob.java
Fixes: #517
Fixes up some issues that arose due to previous refactorings, where collections were improperly modified during traversal, or methods went from blocking operations to returning `Uni`s which went ignored, or active recordings were improperly left running, or duplicate target definitions were not de-duplicated by JVM ID and thus were acted on multiple times.
2. `./smoketest.bash -Ot`
3. Create an automated rule using the JSON below
4. Verify that targets have the active recording created and started
5. Verify that rule archives copies, then prunes extras later
6. Disable rule with `clean` option …
=> fix(rules): rule archiving and re-activation bugfixes

.github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md, .github/workflows/pr-ci.yaml
=> ci(rename): correct CI paths for repo rename

src/main/java/io/cryostat/discovery/DiscoveryNode.java, src/main/java/io/cryostat/graphql/ActiveRecordings.java, src/main/java/io/cryostat/graphql/RootNode.java, src/main/java/io/cryostat/graphql/matchers/LabelSelectorMatcher.java, src/test/java/io/cryostat/graphql/matchers/LabelSelectorMatcherTest.java, src/test/java/itest/GraphQLTest.java, src/test/java/itest/bases/StandardSelfTest.java
Based on: #294 
Continuation of: #316 
2. *...*
=> fix(itest): fix GraphQLTest.java

src/main/java/io/cryostat/recordings/Recordings.java
Fixes: #540 
Consider connectUrl `uploads` as special case to use  `uploads` as the `jvmId`. 
Uploaded archives can now be viewed with Grafana.
1. Built the cryostat container image or use CI snapshot image.
2. Launch local smoketest with `bash smoketest.bash -O`.
3. Upload any JFR file with the UI. The action should complete successfully and the archive should show up.
4. Click on the far-right 3-dot and select `View in Grafana...`. This action should be work as expected.
=> fix(recordings): uploaded archives should be viewable with Grafana

compose/sample-apps.yml
Related to #402
Depends on https://github.com/cryostatio/test-applications/pull/9
2. *...*
=> test(smoketest): use test-applications with agent 0.4.1-snapshot

.dockerignore, .dockerignore.builder, .github/workflows/push-ci.yaml, src/main/docker/Dockerfile.builder
Fixes: #372
Adds `Dockerfile.multiarch`, a multi-stage build that starts with an arch-specific builder and ends with an image that copies all the built assets into the runtime base image. The arch-specific builder picks up the `$TARGETARCH` environment variable and passes that to Maven as `-Dbuild.arch` - see https://github.com/cryostatio/cryostat3/pull/371 .
A manual build for the host machine's native arch would look like:
```
$ podman build --ignorefile .dockerignore.builder --ulimit nofile=4096:4096 . -f src/main/docker/Dockerfile.builder -t quay.io/cryostatcryostat:4.0.0-dev
```
The `--ulimit nofile=4096:4096` works around a …
=> build(multiarch): multistage multiarch builder to ensure native dependencies match arch

.github/workflows/push-ci.yaml
=> ci(oci): enable parallel builds in OCI format

compose/sample_apps/gameserver-jdk11.yml, compose/sample_apps/gameserver-jdk17.yml, compose/sample_apps/gameserver-jdk21.yml
Related to #572
Depends on https://github.com/cryostatio/test-applications/pull/15
See https://github.com/cryostatio/test-applications/pull/14
2. *...*
=> test(gameserver): split sample for JDK versions

.dockerignore.builder, .github/workflows/ci-code-analysis.yml, .github/workflows/pr-ci.yaml, .github/workflows/push-ci.yaml, pom.xml, schema/update.bash, src/main/docker/Dockerfile.builder, src/main/docker/Dockerfile.jvm
See https://github.com/cryostatio/cryostat/pull/373
Based on https://github.com/cryostatio/cryostat/pull/580
2. *...*
=> ci(multiarch): improve build times

pom.xml
See https://github.com/cryostatio/cryostat/pull/600
2. *...*
=> build(deps): bump io.fabric8:kubernetes-client from 6.7.2 to 6.10.0

pom.xml
See https://github.com/cryostatio/cryostat/pull/480
2. *...*
=> build(deps): bump commons-validator:commons-validator from 1.7 to 1.8.0

pom.xml, src/main/java/io/cryostat/discovery/KubeApiDiscovery.java
See https://github.com/cryostatio/cryostat/pull/605
Replaces the Fabric8 Kubernetes Client dependency with an equivalent Quarkus Kubernetes Client extension dependency. This uses the Quarkus BOM version so the dependency is kept at an appropriate version compatible with the Quarkus version, including usability in native mode (not relevant at this time, but interesting).
Since https://github.com/cryostatio/cryostat/pull/601 , Cryostat fails to start on Kubernetes/OpenShift when Kubernetes API discovery is enabled:
```
2024-08-14 14:32:31,741 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): …
```
=> build(deps): replace direct fabric8 kubernetes-client with quarkus kubernetes-client

pom.xml, src/main/resources/application.properties
See https://github.com/cryostatio/cryostat-helm/pull/184
Switches out the HTTP client library used by the S3 (storage) client from JDK urlconnection to Apache HTTP.
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration.html
Apache HTTP should be more performant and robust than urlconnection, and supports the full S3 API feature set.
After splitting out the storage container to a separate Deployment with a separate Service I observe some connection flakiness and instability, where Cryostat API requests dealing with storage (archive actions, querying custom event templates) often respond with sporadic HTTP …
=> build(deps): switch S3 HTTP client from urlconnection to apache

README.md
Related to https://github.com/cryostatio/cryostat-web/pull/1299
2. *...*
=> docs(readme): document frontend dev mode setup

src/main/java/io/cryostat/discovery/ContainerDiscovery.java, src/main/java/io/cryostat/discovery/CustomDiscovery.java, src/main/java/io/cryostat/discovery/Discovery.java, src/main/java/io/cryostat/discovery/DiscoveryNode.java, src/main/java/io/cryostat/discovery/JDPDiscovery.java, src/main/java/io/cryostat/discovery/KubeApiDiscovery.java, src/main/resources/application-dev.properties, src/main/resources/application.properties, src/main/resources/db/migration/V4.0.0__cryostat.sql
See #590
Fixes https://github.com/cryostatio/cryostat/issues/549
Removes the Quarkus-level startup check and lazy initialization of builtin discovery plugins, replacing these with eager initialization within the database migration scripts handled by Flyway.
This ensures that discovery nodes and plugins creation is correctly tied to the database schema, and that the expected nodes and plugins are seeded in the database prior to application startup. This allows for cleaner application restart on an existing database instance, since the node creation/removal logic is no longer tied to the application lifecycle - no need for a startup …
=> chore(db): use Flyway migration to set up discovery plugins

pom.xml, src/main/java/io/cryostat/BuildInfo.java, src/main/java/io/cryostat/Health.java
Related to #550
Stores the output of `git rev-parse` in `META-INF/gitinfo` similar to what the 2.x build did with `git describe`. Then, `GET /health` includes this string in its output as a nested JSON property, rather than replacing the version string.
Easier identification of development builds and linking to exact sources for all builds.
2. `./smoketest.bash -Ok`
3. `http :8080/health`
=> feat(about): reimplement git build info in /health

schema/schema.graphql, src/main/java/io/cryostat/expressions/MatchExpressionEvaluator.java, src/main/java/io/cryostat/targets/Target.java
Related to: https://github.com/cryostatio/cryostat-web/issues/1325
=> chore(matchExpressions): rename target.isAgent match expression to target.agent to fit current nomenclature

schema/schema.graphql, src/main/java/io/cryostat/expressions/MatchExpressionEvaluator.java, src/main/java/io/cryostat/targets/Target.java
This reverts commit 0313522d15c9e43488385d914fb01b7dba711793, but keeps target.agent match expression field.
Related to: https://github.com/cryostatio/cryostat-web/issues/1325
=> chore(matchExpressions): revert #625 rename target.isAgent match expression to target.agent to fit current nomenclature

pom.xml
=> chore(release): set versions for 3.0.2-SNAPSHOT

pom.xml, schema/schema.graphql, src/main/java/io/cryostat/graphql/RecordingLinks.java, src/main/java/io/cryostat/graphql/TargetNodes.java, src/main/java/io/cryostat/recordings/Recordings.java
=> build(deps): update to Quarkus 3.15 LTS

compose/sample_apps/gameserver-jdk11.yml, compose/sample_apps/gameserver-jdk17.yml, compose/sample_apps/gameserver-jdk21.yml, compose/sample_apps/opensearch.yml, compose/sample_apps/quarkus-cryostat-agent.yml, schema/openapi.yaml, src/main/java/io/cryostat/diagnostic/Diagnostics.java, src/main/java/io/cryostat/targets/AgentClient.java, src/main/java/io/cryostat/targets/AgentConnection.java
Related to https://github.com/cryostatio/cryostat/issues/133
Depends on https://github.com/cryostatio/cryostat-core/pull/459
~~**NOTE** Since this depends on an addition to `-core`, which publishes snapshot builds but for which the CI to do so is currently broken, *this cannot be merged* until that CI failure is resolved. Otherwise, Cryostat (and the associated upcoming Agent PR) will fail to build and all CI will be failing.~~
Implements the Agent HTTP delegation side of the MBean operation invocation request, and adds a beta API endpoint which invokes the GC operation on the Agent HTTP or JMX connection to the specified Target …
=> feat(diagnostic): implement diagnostics class with gc invocation operation

compose/s3-seaweed.yml
Related to https://github.com/cryostatio/cryostat-storage/pull/29
https://github.com/cryostatio/cryostat-operator/pull/963
Enables optional at-rest encryption on the storage container.
This adds a small additional layer of security to the object storage. Enabling it in the smoketest helps to ensure it is working transparently.
2. `./smoketest.bash`
3. `podman logs -r -f compose_s3_1` (or whatever the container gets named on your setup) and ensure that the `-filter.encryptVolumeData` flag is passed to `exec weed`
4. Start a recording on Cryostat or the report generator, archive it, and ensure that the archived file …
=> test(smoketest): enable storage encryption

compose/auth_proxy.yml, compose/auth_proxy_https.yml, compose/cryostat-grafana.yml, compose/cryostat.yml, compose/cryostat_docker.yml, compose/cryostat_k8s.yml, compose/db-viewer.yml, compose/db.yml, compose/grafana_no_proxy.yml, compose/jfr-datasource.yml, compose/no_proxy.yml, compose/reports.yml, compose/s3-cloudserver.yml, compose/s3-localstack.yml, compose/s3-minio.yml, compose/s3-none.yml, compose/s3-seaweed.yml, compose/s3_no_proxy.yml, compose/sample_apps/gameserver-jdk11.yml, compose/sample_apps/gameserver-jdk17.yml, compose/sample_apps/gameserver-jdk21.yml, compose/sample_apps/opensearch.yml, compose/sample_apps/quarkus-cryostat-agent.yml, compose/sample_apps/quarkus-cryostat-agent_https.yml, compose/sample_apps/spring-boot-2-7.yml, compose/sample_apps/spring-boot-3.yml, compose/sample_apps/vertx-cryostat-agent.yml, compose/sample_apps/wildfly-23.yml, compose/sample_apps/wildfly-28.yml
Related to #609
1. Restores the Cryostat healthcheck which was disabled in #609. This mysteriously stopped working on that upgrade. Now after updating my workstation to Fedora 40, which comes with newer versions of `docker-compose` and things, it complained that the container did not have a defined healthcheck. Re-enabling the old one now seems to work.
2. Removes the 'version' declarations from compose manifests. The newer `docker-compose` version warns that these declarations are deprecated/obsolete and will be ignored.
After upgrading my workstation from Fedora 39 to 40, these changes are required for `bash smoketest.bash -t` to …
=> test(smoketest): restore healthcheck, remove obsolete version declarations

src/main/java/io/cryostat/events/S3TemplateService.java
Related to #718
Tolerate already existing Event Templates when loading from container filesystem at startup.
Declarative configurations for Event Templates (ie defining them by mounting files to the container, ex. by Operator CR linking to ConfigMaps) should be tolerant of the templates already existing, since they will already exist in the remote S3 storage service if the Cryostat container has been restarted, for example.
1. See associated Helm PR. Deploy with that, then `oc rollout restart deployment cryostat-v4` to trigger the case where the template already exists in storage. With this PR, Cryostat should log a warning and …
=> fix(eventtemplates): log warning and continue if declarative Event Template already exists

schema/openapi.yaml, src/main/java/io/cryostat/Producers.java, src/main/java/io/cryostat/recordings/ActiveRecordings.java, src/main/java/io/cryostat/recordings/ArchiveRequestGenerator.java, src/main/java/io/cryostat/recordings/ArchivedRecordings.java, src/main/java/io/cryostat/recordings/LongRunningRequestGenerator.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/reports/MemoryCachingReportsService.java, src/main/java/io/cryostat/reports/Reports.java, src/main/java/io/cryostat/reports/ReportsService.java, src/main/java/io/cryostat/reports/ReportsServiceImpl.java, src/main/java/io/cryostat/reports/StorageCachingReportsService.java, src/test/java/io/cryostat/reports/ReportsTest.java, src/test/java/itest/RecordingWorkflowTest.java, src/test/java/itest/ReportGenerationTest.java, src/test/java/itest/TargetRecordingPatchTest.java, src/test/java/itest/UploadRecordingTest.java
Fixes #286
Hi, 
This adds a prototype for long running API operations (first step of https://github.com/cryostatio/cryostat/issues/286).
The workflow proceeds as described in the issue:
- Cryostat receives a patch request to archive a recording
- Basic validation is done (check that target is valid and that the recording exists)
- Following this an ArchiveRequest is created that tracks a job ID and the requested recording
- The archive request is then passed on to the ArchiveRequestGenerator (works similarly to the InterruptibleReportsGenerator)
- ArchiveRequestGenerator performs the archiving on a separate thread, firing a notification to the web client for success or failure which includes the job ID
TODO: Web Client needs to be adjusted to account for the new notifications, refreshing …
=> feat(async): long-running async job API

src/main/java/io/cryostat/discovery/Discovery.java, src/main/java/io/cryostat/targets/Target.java
Hi,
This addresses https://github.com/cryostatio/cryostat/issues/685 , adding URI range validation to discovery plugins and related targets, and validating the target connecturl range in the prePersist hooks.
=> fix(uri-validation): Validate URI ranges for discovery plugins and related targets

src/main/java/io/cryostat/expressions/MatchExpressionEvaluator.java, src/test/java/io/cryostat/expressions/MatchExpressionsTest.java
See https://github.com/cryostatio/cryostat/pull/733#issuecomment-2524038050
Related to https://github.com/cryostatio/cryostat/issues/727
Related to https://github.com/cryostatio/cryostat/issues/548
See https://github.com/cryostatio/cryostat/pull/733#issuecomment-2524038050
Enables the creation of match expressions that evaluate the JFR event types available on a given target JVM. This probably isn't very useful for Stored Credentials, but for Automated Rules it will couple well with #733 , as well as with custom application-level JFR events. It becomes possible to define Automated Rules that use a preset or custom event template …
=> feat(matchexpressions): expressions can reference target JFR event type IDs

src/main/java/io/cryostat/rules/RuleExecutor.java, src/main/java/io/cryostat/rules/RuleService.java
Fixes: #731
Adds logic for automatic retry when an automated rule is activated but fails. This can happen because the discovered target application is not yet actually ready to accept requests, or because of some network hiccup, etc. Previously if an automated rule activation failed then Cryostat would never retry and the rule would not take effect on the target, until some other event caused a reactivation (rule disable/reenable, stored credentials added, target modified, target lost/found).
Increases reliability of automated rules.
1. Deploy on k8s, ex. using Helm chart
2. Deploy sample application. I used the Operator's `make …
=> fix(rules): automatic refire with backoff

compose/cryostat.yml, smoketest.bash, src/main/java/io/cryostat/ConfigProperties.java, src/main/java/io/cryostat/discovery/Discovery.java, src/main/java/io/cryostat/targets/AgentClient.java, src/main/java/io/cryostat/targets/AgentConnection.java, src/main/java/io/cryostat/util/URIUtil.java, src/main/resources/application.properties
Hi,
This is the other half to https://github.com/cryostatio/cryostat-agent/pull/554 , enforcing TLS by default on the server side for agent communication. Controlled by a configuration option cryostat.agent.tls.enabled
Addresses https://github.com/cryostatio/cryostat/issues/686
=> fix(tls): use TLS by default in the Agent Client

src/test/java/io/cryostat/resources/S3StorageResource.java, src/test/java/itest/CustomEventTemplateTest.java, src/test/java/itest/GraphQLTest.java, src/test/java/itest/RecordingWorkflowTest.java, src/test/java/itest/ReportGenerationTest.java
Related to #759
Sets up the tests (unit and integration) to deploy `cryostat-storage` rather than `localstack` as the S3 storage instance.
This allows us to have some level of automated integration testing between Cryostat and our SeaweedFS soft fork to ensure things are working as expected.
2. *...*
=> test(storage): deploy cryostat-storage rather than localstack

.github/workflows/pr-ci.yaml, .github/workflows/push-ci.yaml
See https://github.com/cryostatio/cryostat-core/pull/494
2. *...*
=> ci(criu): add CRIU PPA for Podman dependency

compose/cryostat_docker.yml, compose/cryostat_k8s.yml, pom.xml, src/main/docker/Dockerfile.jvm
Based on https://github.com/cryostatio/cryostat/pull/651
Depends on https://github.com/cryostatio/cryostat/pull/651
Depends on https://github.com/cryostatio/cryostat-operator/pull/953
Depends on https://github.com/cryostatio/cryostat-storage/pull/27
Depends on https://github.com/cryostatio/openshift-oauth-proxy/pull/9
Depends on https://github.com/cryostatio/cryostat-reports/pull/276
Depends on https://github.com/cryostatio/jfr-datasource/pull/327
Depends on https://github.com/cryostatio/cryostat-agent/pull/561
Fixes https://github.com/cryostatio/cryostat/issues/650
*This change allows an environment variable to be configured so …
=> chore(container): upgrade to UBI9

src/main/docker/Dockerfile.jvm, src/main/docker/include/rule_presets/quarkus.json, src/main/java/io/cryostat/ConfigProperties.java, src/main/java/io/cryostat/rules/Rules.java, src/main/resources/application.properties, src/test/java/itest/PresetRulesIT.java
Based on https://github.com/cryostatio/cryostat/pull/735
Depends on https://github.com/cryostatio/cryostat/pull/735
Fixes https://github.com/cryostatio/cryostat/issues/548
Fixes https://github.com/cryostatio/cryostat/issues/727
Adds a declarative configuration directory for Automated Rules and implements loading definitions from this directory at startup.
This will allow users to preload Automated Rules into their Cryostat installations without needing to go through the web UI or API calls. It also allows us to ship pre-written Rule definitions as part of the base container image.
For practical usage, end users who are using JMX for …
=> feat(rules): implement declarative Automated Rules

src/main/java/io/cryostat/reports/Reports.java, src/test/java/io/cryostat/reports/ReportsTest.java, src/test/java/itest/RecordingWorkflowTest.java
Fixes #762
Hi,
This addresses https://github.com/cryostatio/cryostat/issues/762 . The location header that was returned with the request when the cache missed and the report needed to be generated was incorrect, this caused the following sequence of events to happen:
- Client sends report generation request
- Server sees that the report isn't in the cache, kicks off report generation and tries to return an intermediate response to the client
- Location Header on the last step was incorrect causing an exception which returned a 400 to the client despite report generation proceeding as expected.
-  Subsequent requests succeeded because at that point the report was cached.
This fixes the location header and adds a missing content type header to active report generation.
=> fix(api): Fix location header for archived report generation

src/main/resources/application.properties
=> feat(agent): add option to disable hostname verification

src/main/java/io/cryostat/targets/AgentConnection.java
Related to #747
See also https://github.com/cryostatio/cryostat/pull/776
Corrects a logical error in the Agent TLS connection enforcement.
2. `./smoktest.bash -O -t quarkus-cryostat-agent`
3. Ensure that all the usual tasks complete successfully when selecting the Agent HTTPS target
=> fix(agent): fix TLS enforcement for Agent instances

src/main/java/io/cryostat/JsonRequestFilter.java, src/main/java/io/cryostat/expressions/MatchExpressionEvaluator.java, src/main/java/io/cryostat/targets/TargetUpdateService.java, src/main/resources/application-dev.properties
Fixes: #753
Ensures transaction context is active when processing credential deletions in particular situations.
2. Apply this patch:
```patch
diff --git a/src/main/java/io/cryostat/discovery/Discovery.java b/src/main/java/io/cryostat/discovery/Discovery.java
index 508dbd55..0279cc46 100644
--- a/src/main/java/io/cryostat/discovery/Discovery.java
+++ b/src/main/java/io/cryostat/discovery/Discovery.java
@@ -215,6 +215,9 @@ public class Discovery {
remoteURI));
}
+        if (true) {
+            throw new BadRequestException();
+        }
if (agentTlsRequired && …
```
=> fix(credentials): ensure deletion occurs within transaction context

pom.xml, src/main/docker/include/rule_presets/hibernate.json, src/main/docker/include/rule_presets/quarkus.json, src/main/docker/include/template_presets/hibernate.jfc, src/main/docker/include/template_presets/quarkus.jfc, src/test/java/itest/PresetRulesIT.java, src/test/java/itest/PresetTemplatesIT.java
Fixes: #736
See also #548
Depends on https://github.com/cryostatio/cryostat/pull/749
Based on https://github.com/cryostatio/cryostat/pull/749
Adds a Preset Event Template for Hibernate JFR events, which are enabled by the `hibernate-jfr` dependency. Any application using Hibernate which also has this JAR on its classpath should have the relevant JFR event types registered, and they can be emitted simply by starting a recording with them enabled. Also adds an Automated Rule which detects the presence of these event types in the target JVM, for ease of enablement by the end user.
Provides a quick and easy way for Cryostat + Hibernate …
=> feat(preset): add preset template and rule for Hibernate JFR

src/main/java/io/cryostat/recordings/LongRunningRequestGenerator.java
Fixes: [#761](https://github.com/cryostatio/cryostat/issues/761)
Fixes the notification category for ArchiveRecordingFailure and GrafanaUploadFailure to bring them in line with what the web frontend expects.
1. Run cryostat via ./mvnw quarkus:dev or smoketest
2. Fail to archive a recording (Can induce this by throwing an exception at the start of the try/catch in LongRunningRequestGenerator.java (line 71 for archive, 90, 107 for grafana))
3. Observe that the notifications are emitted.
=> fix(notifications): Fix notification String constants

src/main/java/io/cryostat/recordings/RecordingHelper.java
Fixes #781 
During the development of the long running api framework this notification got removed as it was causing problems with the implementation at that time. After iterating more and finishing the implementation of the framework I missed adding this back. This adds it back, fixing 781 and making automated rules archiving behave as expected in the UI.
=> fix(notifications): Restore missing notification when archiving recordings

compose/cryostat.yml, compose/sample_apps/quarkus-petclinic.yml
Depends on https://github.com/cryostatio/test-applications/pull/32
Adds a more complex sample application for testing.
This sample application is more interactive than many of the others, and this one includes `quarkus-jfr` and `hibernate-jfr` so can be used as a test for the functionalities integrating those event templates and automated rules.
See https://github.com/cryostatio/cryostat/pull/750
See https://github.com/cryostatio/cryostat/pull/733
2. `./smoketest.bash -Ot quarkus-petclinic`. If https://github.com/cryostatio/test-applications/pull/32 isn't merged yet, check out that PR and `cd quarkus-petclinic ; …
=> test(smoketest): add quarkus-petclinic sample

src/main/java/io/cryostat/events/SerializableEventTypeInfo.java
Related to https://github.com/cryostatio/cryostat/issues/803
Depends on https://github.com/cryostatio/cryostat-core/pull/507
JFR events do not necessarily have the `label` attribute, which in the JMC API is called `name`. The OpenJDK built-in events all happen to have this attribute, but custom application or framework events may not, and notably GraalVM has at least one event type (`EveryChunkPeriodEvents`) which has no label.
Unlabelled JFR events would cause an NPE on `/api/v4/targets/{id}/events` query before this.
1. Combine with https://github.com/cryostatio/cryostat-core/pull/507 and …
=> fix(events): permit JFR Event Types without label attributes

pom.xml, src/test/java/io/cryostat/resources/AgentApplicationResource.java, src/test/java/io/cryostat/resources/AuthProxyContainer.java, src/test/java/itest/AgentDiscoveryIT.java, src/test/java/itest/bases/HttpClientTest.java, src/test/java/itest/bases/StandardSelfTest.java
Related to #42
Depends on https://github.com/cryostatio/cryostat/pull/767
2. *...*
=> test(agent): add Agent itest

compose/sample_apps/micronaut-cryostat-agent.yml
Depends on https://github.com/cryostatio/test-applications/pull/39
Related to https://github.com/cryostatio/test-applications/issues/20
2. *...*
=> test(smoketest): add micronaut sample

src/test/java/itest/HealthIT.java
=> test(health): check for reports, build info

smoketest.bash
=> chore(smoketest): swap busybox volume helper for ubi-micro

.github/workflows/pr-ci.yaml, .github/workflows/push-ci.yaml, README.md, compose/s3-localstack.yml, compose/s3-minio.yml, compose/sample_apps/opensearch.yml, src/main/resources/application-dev.properties, src/main/resources/application-test.properties
=> chore(quay): switch more images to quay.io alternatives

.github/workflows/pr-ci.yaml, .github/workflows/push-ci.yaml
=> ci(github): remove privileged step

.github/workflows/pr-ci.yaml, .github/workflows/push-ci.yaml
=> ci(github): use tilde for runner home path

.github/workflows/pr-ci.yaml, .github/workflows/push-ci.yaml
=> ci(github): use explicit path for runner home

.github/workflows/pr-ci.yaml, .github/workflows/push-ci.yaml
=> ci(github): re-enable qemu for single-arch testcontainers

.github/workflows/pr-ci.yaml, src/main/resources/application-test.properties, src/test/java/io/cryostat/AbstractTestBase.java
=> test(storage): deploy cryostat-storage instead of localstack

.github/workflows/pr-ci.yaml, .github/workflows/push-ci.yaml
Disable testcontainers ryuk in CI. The quay.io image in use is not multiarch and fails to start in arm64 CI. ryuk is used to reap containers after the test run, but we don't need that in CI since the job will end and the runner will exit anyway.
=> ci(github): disable ryuk

schema/openapi.yaml, schema/schema.graphql, src/main/java/io/cryostat/MessageCodecs.java, src/main/java/io/cryostat/discovery/JDPDiscovery.java, src/main/java/io/cryostat/events/S3TemplateService.java, src/main/java/io/cryostat/jmcagent/JMCAgentProbes.java, src/main/java/io/cryostat/jmcagent/S3ProbeTemplateService.java, src/main/java/io/cryostat/rules/RuleExecutor.java, src/main/java/io/cryostat/rules/RuleService.java, src/test/java/itest/RulesPostFormIT.java, src/test/java/itest/RulesPostJsonIT.java
Fixes: #878
Related to https://github.com/cryostatio/cryostat/pull/732
In #732 the RuleService was split up and the RuleExecutor was extracted out as a separate component. These two communicate with each other over the EventBus. The error handling retry/backoff behaviour was left within the RuleService, and the RuleExecutor would simply throw uncaught exceptions if anything failed during eventbus message processing.
This change ensures that exceptions thrown during RuleExecutor processing are passed back to the RuleService so that the error handling logic can be correctly invoked in those cases, as well.
The particular exception …
=> fix(rules): correct error handling behaviour across component boundary

smoketest.bash
Related to #857
Ensure the `credentials` volume and `_helper` container are cleaned up so that subsequent re-runs have a clean slate.
=> test(smoketest): ensure removal of credentials volume

src/main/java/io/cryostat/reports/Reports.java, src/test/java/io/cryostat/reports/ReportsTest.java
See #859
Related to #892
Adds an additional label to snapshot recordings created by `POST /api/v4.1/targets/{targetId}/reports` requests.
The label will be copied to the archived version of the snapshot. Later, when the user is done looking at the automated analyses results and doesn't want/need the archived recordings anymore, the label makes it quick and easy to select the recordings which were created by target automated analysis for deletion.
2. `./smoketest.bash -O`, optionally add `-r` or `-t quarkus-cryostat-agent`
3. Wait for everything to come up and open UI
4. Select Cryostat itself as the target, …
=> feat(automated-analysis): include label for grouping target-analysis recordings

src/main/java/io/cryostat/discovery/DiscoveryNode.java
Related to #870
See https://github.com/cryostatio/cryostat/pull/725#issuecomment-2863344308
Fixes a bug introduced in #870 refactoring where the new `DiscoveryNode.byTypeWithName` query and associated Java method are used improperly. This query is expected to return back a list of nodes that match the given node type and name, with an additional predicate function to filter the results further in cases where more than one result is expected. If there are no matching results then a new node is created, and an additional given customizer function is used to apply specific changes to that node (ex. so that it would match the query …
=> fix(discovery): apply predicate to node queries

compose/cryostat.yml, src/main/java/io/cryostat/credentials/Credentials.java
Related to: https://github.com/cryostatio/cryostat/issues/728
Fixes an issue found in https://github.com/cryostatio/cryostat-operator/pull/1089
While the matchExpression field in the Credential class is already marked as cascading (CascadeType.ALL) we reference it in the query to check whether the Credential we're creating already exists before the matchExpression is persisted. This fixes that by persisting it after it's created by the json mapper and adds some additional logging to the trace and warn levels.
To test:
- Create a directory 'credentials' and add a json credential file to it (credential.json)
{
"username": "user",
"password": "pass",
"matchExpression": "false"
}
- Build the cryostat container (./mvnw package -Dquarkus.docker.buildx.platform=linux/amd64)
- Run smoketest (bash …
=> fix(credentials): Persist matchExpression when creating credentials from files

src/main/java/io/cryostat/ConfigProperties.java, src/main/java/io/cryostat/DeclarativeConfiguration.java, src/main/java/io/cryostat/credentials/Credentials.java, src/main/java/io/cryostat/events/S3TemplateService.java, src/main/java/io/cryostat/jmcagent/S3ProbeTemplateService.java, src/main/java/io/cryostat/rules/Rules.java, src/main/java/io/cryostat/security/TrustStore.java, src/main/resources/application.properties
Related to https://github.com/cryostatio/cryostat/issues/718
See also #912
Fixes #916
Refactors to extract a shared utility class across various components that have the common "declarative configuration" concept, ie. directories that can be mounted to the Cryostat container allowing the user to define resources without needing to deploy Cryostat and go through the API (ex. Automated Rules as JSON files). The shared utility adds some additional logic for handling of symbolic links.
The symbolic link handling addition deals with the case where Kubernetes Secrets and ConfigMaps are mounted to Cryostat by the Operator or Helm Chart. …
=> fix(config): handle symlinks in declarative config loading

src/main/java/io/cryostat/rules/Rules.java, src/test/java/io/cryostat/rules/RulesTest.java
Related to https://github.com/cryostatio/cryostat-web/issues/1581
Allows more Automated Rule fields to be updated by the existing PATCH endpoint. Rule names cannot be modified this way but anything else can be.
Required for upcoming frontend feature to allow editing existing Rules or duplicating Rules.
2. *...*
=> feat(rules): allow patching of all rule fields

src/main/docker/Dockerfile.jvm
See #932
See ex. https://github.com/cryostatio/cryostat/actions/runs/15612274492/job/43975946398
2. *...*
=> build(oci): remove broken conditional logic

src/main/java/io/cryostat/discovery/KubeApiDiscovery.java, src/main/java/io/cryostat/discovery/KubeEndpointSlicesDiscovery.java, src/main/resources/application.properties
Fixes: #722
Depends on #689
Based on #689
Depends on #740
Handles the `*` value in Kubernetes discovery namespaces as a wildcard indicating "All Namespaces". When this is found then, rather than creating an Endpoints Informer for each target namespace, Cryostat creates a single Informer for Endpoints in any namespace in the cluster. A few pieces of supporting logic are modified to suit this change, ex. grabbing the client-side cache (in Cryostat application memory) and doing per-namespace filtering of Endpoints objects found in that cluster-wide Informer, rather than having each Informer's cache already be segmented by namespace. …
=> feat(k8s): implement wildcard All Namespaces discovery

src/main/java/io/cryostat/reports/Reports.java, src/test/java/io/cryostat/reports/ReportsTest.java
See cryostatio/cryostat-web#1589
Related to #842
Corrects a `Location` response header that points to `api/v4` when it should be `api/v4.1`. The `cryostat-web` client does not actually use this `Location` header, but it should still be corrected.
=> fix(api): Location header points to correct API version path

.github/workflows/pr-ci.yaml, .github/workflows/push-ci.yaml
=> ci(cache): set cache download timeout

compose/sample_apps/quarkus-cryostat-agent.yml, compose/sample_apps/quarkus-petclinic.yml, pom.xml, src/main/docker/Dockerfile.jvm, src/main/resources/application-test.properties, src/main/resources/application.properties, src/test/java/io/cryostat/resources/AgentApplicationResource.java, src/test/java/io/cryostat/resources/AuthProxyContainer.java, src/test/java/io/cryostat/resources/S3StorageBucketedMetadataResource.java, src/test/java/io/cryostat/resources/S3StorageObjectMetadataResource.java, src/test/java/itest/AgentDiscoveryIT.java, src/test/java/itest/AgentDiscoveryTest.java, src/test/java/itest/CustomTargetsTest.java, src/test/java/itest/RecordingWorkflowBucketedMetadataTest.java, src/test/java/itest/RecordingWorkflowTest.java, src/test/java/itest/bases/HttpClientTest.java
Related to #759
1. Fixes up the agent discovery integration test, which tests the integration of Cryostat + oauth2_proxy + cryostat-agent by simply ensuring that an agent instance is able to register with Cryostat via the proxy, and that the agent eventually becomes discoverable and listed in Cryostat's API. A key part of this is the `--network-alias` to `quarkus.test.arg-line` change from the resource class into `pom.xml`, which reinstates the configuration so that the Cryostat container under test is resolvable by the hostname `cryostat` within the test network. This test is disabled in PR CI because of the ["Broken …
=> test(agent): agent discovery test

schema/openapi.yaml, src/main/docker/Dockerfile.jvm
See #952
See https://github.com/cryostatio/cryostat-operator/pull/1138
See https://github.com/cryostatio/cryostat-helm/pull/257
Removes the `-Dquarkus.http.host=0.0.0.0` system property present in the default `JAVA_OPTS_APPEND` environment variable, and sets this as a `QUARKUS_HTTP_HOST=0.0.0.0` environment variable instead.
1. Setting it as an environment variable is easier to manage, since the variable is a single key-value pair. The system property within `JAVA_OPTS_APPEND` is part of multiple key-value pairs, and more easily (accidentally) overridden.
2. Worse, the system property may not be accidentally overridden - it may be …
=> fix(dockerfile): remove system property binding quarkus.http.host to 0.0.0.0

pom.xml
=> chore(deps): upgrade Quarkus to 3.15.6.1

src/main/java/io/cryostat/ConfigProperties.java, src/main/java/io/cryostat/events/TargetEventTemplates.java, src/main/java/io/cryostat/recordings/ActiveRecording.java, src/main/java/io/cryostat/recordings/RecordingHelper.java, src/main/java/io/cryostat/targets/TargetConnectionManager.java, src/main/java/io/cryostat/targets/TargetUpdateJob.java, src/main/resources/application.properties, src/test/java/io/cryostat/recordings/ActiveRecordingsTest.java
Fixes: #967
Removes thread locking structures and maximum open connections logic from the TargetConnectionManager.
See #967
2. `./smoktest.bash -O -r -t quarkus-cryostat-agent,wildfly-28`
3. Click around the UI, wait for agent instances to push harvested recordings, etc. and make sure everything is still working the same as usual.
=> chore(connection): remove TargetConnectionManager locking structures

src/main/java/io/cryostat/ConfigProperties.java, src/main/java/io/cryostat/discovery/KubeEndpointSlicesDiscovery.java, src/main/java/io/cryostat/targets/TargetConnectionManager.java, src/main/java/io/cryostat/targets/TargetsModule.java, src/main/java/io/cryostat/util/URIRange.java, src/main/java/io/cryostat/util/URIUtil.java, src/main/resources/application.properties
Fixes: #964
1. Adds a boolean config property (defaults to `true`) to apply a DNS name transformation to EndpointSlice addresses which are IPv4. Rather than using the simple direct IPv4 `1.2.3.4 `address as the hostname, the transformation changes this to the k8s DNS `1-2-3-4.$namespace.pod` hostname. This seems to be useful for at least some network stacks, ex. in `kind`.
2. Adds handling for IPv6 addresses, where the URL containing an IPv6 address as the hostname must enclose the address in square brackets. ~~This doesn't actually fix IPv6 connectivity issues at the moment - connection failures further down in JMC code or even …
=> fix(discovery): handle k8s IPv6 EndpointSlices
